language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
before_deploy:
  - cargo build --release
deploy:
  provider: releases
  file: "target/release/brightness_control"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: 24OjLcQbpaiqXaBLJLwOM7rVV3vTEw1CR6f//rD4egDHestfRhmuSLIK3eNs2X1hWQlcO9 GZMMffYDJurte8bTJzceJG5oKHEF/W4lGGNDYIgiiomvt5wMVqCr8E007UxOwBiIGYQojUWjrFmwGasvOE uvDg7sPZz6NPVuA47Z+/BM7Gfyw5QSuLfV4K0wjlmkC7MRlgWDDpRDnu+be1LRx1cn7jnRu+pQfG5OwSVs 45hctHAR6ynl+iUpF8saDA9kesFl5IvIvV6VoDJ0VWJyf0SGZ8aDyYyN0o4MSS0nKgLALlUvFOtTuLk9hr D9uuN8gg8ldrb44fQv0Y6gwUhV2TKCfx05P/+UbS0dPxQvpI8oeHxpGDYzr5Ebtzmd2EwK3xLI8HWqrfMT KJd48/LzaOfH5eUxd3NJr2x0OjQ3w+eKWmbfZ1TcTTtxKabGAJiw+e5Q7ux1q1ZHWtiDlf/wRH5fYBnj0T 28mI+RliBYEq6BluTuIEQ/L/IR/n50CVhOtD4ZOZXr3PW3OR6706x1lCGIMTVkYxe/et7+F+BSrjVIY20W Q2alsppvFgPW1aD47mzTNC2arp60FbMSuADbOWNGw9ruwC82adhhHcNW9jfW0dpvsNdQZeX1NXaGkD9feS 8a+9RxUbh3Ef6H7nsjBfuTQOLMbdCIYVC82pXdY=
