[package]
name = "brightness_control"
version = "1.1.2"
authors = ["Sridaran Thoniyil <sri7thon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "2.0.2"

[features]
# reconfigures display if xrandr call fails
auto-reconfigure = []

# use redshift for blue light filter
redshift = []

##########################
# this is not a feature
default = []
