# v1.4.2
# ^ KEEP THIS IN THE TEMPLATE
# Every time the template is updated, the current version is put at the top
# You can delete it in your own config, but this should stay in the template

# If set to false, uses xrandr --gamma when toggling the nightlight
# If set to true, uses the redshift program instead of xrandr for the nightlight
# However, the brightness will still be controlled by xrandr
# If you are using this option, make sure that you have followed the
# instructions from the "Configuring Redshift" section of the README
use_redshift = false

# If set to false, the daemon will not wait to see if its xrandr updates are
# returning normally
# This allows the daemon to launch xrandr processes asynchronously, allowing the
# daemon to process each individual client command faster
# Calls to xrandr will fail if a monitor is disconnected without the display being reconfigured (brightness_control -c)
# If set to true, the daemon will wait for each xrandr process to terminate
# before processing the next client command
# This means that successive xrandr calls will not fail
#
# HOWEVER, *connecting* a new display will not make xrandr throw an error
# When connecting a new display, use `brightness_control -c` to apply settings
# to that display
auto_reconfigure = true

[fade_options]
# the highest brightness shift that does not use fading
# to disable fading altogether, set this to 100
# the default is for any shift greater than "2%" to use fading
threshold = 2

# the duration in milliseconds for a fade to complete
total_duration = 400

# the duration in milliseconds of each individual brightness level over the
# course of the fade
#
# if you divide "fade_duration" by "fade_step_duration", you get the total
# number of individual steps over the course of each fade
step_duration = 20
