# v1.7.0
# ^ KEEP THIS IN THE TEMPLATE
# Every time the template is updated, the current version is put at the top
# You can delete it in your own config, but this should stay in the template

# If set to false, uses xrandr --gamma when toggling the nightlight
# If set to true, uses the redshift program instead of xrandr for the nightlight
# However, the brightness will still be controlled by xrandr
# If you are using this option, make sure that you have followed the
# instructions from the "Configuring Redshift" section of the README
use_redshift = false

# If set to false, the daemon will not wait to see if its xrandr updates are
# returning normally
# This allows the daemon to launch xrandr processes asynchronously, allowing the
# daemon to process each individual client command faster
# Calls to xrandr will fail if a monitor is disconnected without the display being reconfigured (brightness_control -c)
# If set to true, the daemon will wait for each xrandr process to terminate
# before starting to fade
# This means that successive xrandr calls will not fail
#
# HOWEVER, *connecting* a new display will not make xrandr throw an error
# When connecting a new display, use `brightness_control -c` to apply settings
# to that display
auto_remove_displays = true

# determines which monitors to affect when no monitor override is specified on the command line
[monitor_default_behavior]
# OPTIONS (uncomment ONE block)
#
##########################
# type = "Specified"
# adapter_name = "<Specified Adapter Name>"
##########################
# type = "Active"
##########################
# # NOTE: this affects disabled monitors as well, meaning that when you do `get --brightness` without an override, it would return everything
# # you usually don't want this behavior
# type = "All"
##########################
type = "Enabled"
##########################

[nightlight_options]
# When use_redshift is set to false, BrightnessControl uses xrandr --gamma to
# emulate a nightlight
# The format is R:G:B, where each number is a multiplier for its corresponding
# color
# This default value was obtained through testing
xrandr_gamma = "1.0:0.7:0.45"

# Redshift has a -o flag that takes in the desired color temperature in Kelvin
# Lower values are "warmer" and higher values are "cooler"
# https://en.wikipedia.org/wiki/Color_temperature
redshift_temperature = 1400

[fade_options]
# the highest brightness shift that does not use fading automatically
# to disable automatic fading altogether, set this to 100
# the default is for any shift greater than "2%" to use fading
#
# you can modify this depending on your usage
# for example, with the default config, you can use 2% increments/decrements
# for manual adjustments while using 10% adjustments for coarse-grained
# adjustments
threshold = 2

# the duration in milliseconds for a fade to complete
total_duration = 400

# the duration in milliseconds of each individual brightness level over the
# course of the fade
#
# the default value of "20" was determined through testing
# because the xrandr processes are launched asynchronously, 20 milliseconds
# gives each process sufficient time to terminate
#
# if you divide "fade_duration" by "fade_step_duration", you get the total
# number of individual steps over the course of each fade
step_duration = 20
